// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AppControllerPingData, AppControllerPingResponses, DraftTransactionsControllerCreateDraftTransactionData, DraftTransactionsControllerCreateDraftTransactionResponses, DraftTransactionsControllerGetDraftTransactionData, DraftTransactionsControllerGetDraftTransactionResponses, EfiControllerBaseData, EfiControllerBaseResponses, EfiControllerHandleNotificationData, EfiControllerHandleNotificationResponses, TransactionsControllerCreateData, TransactionsControllerCreateFromDraftData, TransactionsControllerCreateFromDraftResponses, TransactionsControllerCreateResponses, TransactionsControllerFindByReferenceIdData, TransactionsControllerFindByReferenceIdResponses, TransactionsControllerFindOneData, TransactionsControllerFindOneResponses, TransactionsControllerRefundData, TransactionsControllerRefundResponses, TransfersControllerCreateData, TransfersControllerCreateResponses, TransfersControllerFindOneData, TransfersControllerFindOneResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const appControllerPing = <ThrowOnError extends boolean = false>(options?: Options<AppControllerPingData, ThrowOnError>) => (options?.client ?? client).get<AppControllerPingResponses, unknown, ThrowOnError>({ url: '/payment/ping', ...options });

export const transactionsControllerCreate = <ThrowOnError extends boolean = false>(options: Options<TransactionsControllerCreateData, ThrowOnError>) => (options.client ?? client).post<TransactionsControllerCreateResponses, unknown, ThrowOnError>({
    url: '/payment/transactions',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const transactionsControllerCreateFromDraft = <ThrowOnError extends boolean = false>(options: Options<TransactionsControllerCreateFromDraftData, ThrowOnError>) => (options.client ?? client).post<TransactionsControllerCreateFromDraftResponses, unknown, ThrowOnError>({
    url: '/payment/transactions/from-draft',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const transactionsControllerFindOne = <ThrowOnError extends boolean = false>(options: Options<TransactionsControllerFindOneData, ThrowOnError>) => (options.client ?? client).get<TransactionsControllerFindOneResponses, unknown, ThrowOnError>({ url: '/payment/transactions/{id}', ...options });

export const transactionsControllerFindByReferenceId = <ThrowOnError extends boolean = false>(options: Options<TransactionsControllerFindByReferenceIdData, ThrowOnError>) => (options.client ?? client).get<TransactionsControllerFindByReferenceIdResponses, unknown, ThrowOnError>({ url: '/payment/transactions/reference/{referenceId}', ...options });

export const transactionsControllerRefund = <ThrowOnError extends boolean = false>(options: Options<TransactionsControllerRefundData, ThrowOnError>) => (options.client ?? client).put<TransactionsControllerRefundResponses, unknown, ThrowOnError>({
    url: '/payment/transactions/{id}/refund',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const efiControllerHandleNotification = <ThrowOnError extends boolean = false>(options?: Options<EfiControllerHandleNotificationData, ThrowOnError>) => (options?.client ?? client).post<EfiControllerHandleNotificationResponses, unknown, ThrowOnError>({ url: '/payment/webhook/efi/pix', ...options });

export const efiControllerBase = <ThrowOnError extends boolean = false>(options?: Options<EfiControllerBaseData, ThrowOnError>) => (options?.client ?? client).post<EfiControllerBaseResponses, unknown, ThrowOnError>({ url: '/payment/webhook/efi', ...options });

export const draftTransactionsControllerGetDraftTransaction = <ThrowOnError extends boolean = false>(options: Options<DraftTransactionsControllerGetDraftTransactionData, ThrowOnError>) => (options.client ?? client).get<DraftTransactionsControllerGetDraftTransactionResponses, unknown, ThrowOnError>({ url: '/payment/draft-transactions/{referenceId}', ...options });

export const draftTransactionsControllerCreateDraftTransaction = <ThrowOnError extends boolean = false>(options: Options<DraftTransactionsControllerCreateDraftTransactionData, ThrowOnError>) => (options.client ?? client).post<DraftTransactionsControllerCreateDraftTransactionResponses, unknown, ThrowOnError>({
    url: '/payment/draft-transactions',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const transfersControllerCreate = <ThrowOnError extends boolean = false>(options: Options<TransfersControllerCreateData, ThrowOnError>) => (options.client ?? client).post<TransfersControllerCreateResponses, unknown, ThrowOnError>({
    url: '/payment/transfers',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const transfersControllerFindOne = <ThrowOnError extends boolean = false>(options: Options<TransfersControllerFindOneData, ThrowOnError>) => (options.client ?? client).get<TransfersControllerFindOneResponses, unknown, ThrowOnError>({ url: '/payment/transfers/{id}', ...options });
