// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type CardDto = {
    holderName: string;
    number: string;
    expirationDate: string;
    cvv: string;
};

export type CreateTransactionDto = {
    method: 'pix' | 'credit_card';
    /**
     * Card is required when method is credit_card
     */
    card?: CardDto;
    /**
     * Amount in cents
     */
    amount: number;
    referenceId: string;
};

export type GetTransactionDto = {
    id: string;
    originalAmount: number;
    amount: number;
    refundedAmount: number;
    method: 'pix' | 'credit_card';
    status: 'pending' | 'success' | 'refunded' | 'partially_refunded' | 'canceled';
    gatewayTransactionId: string;
    referenceId: string;
    gateway: string;
    pixCode: string;
    pixExpiration: string;
};

export type CreateTransactionFromDraftDto = {
    method: 'pix' | 'credit_card';
    /**
     * Card is required when method is credit_card
     */
    card?: CardDto;
    referenceId: string;
};

export type RefundTransactionDto = {
    /**
     * Amount to be refunded
     */
    amount: number;
};

export type GetDraftTransactionDto = {
    id: string;
    amount: number;
    allowedMethods: Array<'pix' | 'credit_card'>;
    status: 'pending' | 'requested' | 'concluded' | 'canceled' | 'expired';
    referenceId: string;
    expiresAt: string;
};

export type CreateDraftTransactionDto = {
    /**
     * Amount in cents
     */
    amount: number;
    allowedMethods: Array<'pix' | 'credit_card'>;
    referenceId: string;
    expiresAt: string;
};

export type CreateTransferDto = {
    /**
     * Amount in cents
     */
    amount: number;
    method: 'pix';
    referenceId: string;
};

export type GetTransferDto = {
    id: string;
    amount: number;
    method: 'pix';
    status: 'pending' | 'success' | 'failed';
    gatewayTransferId: string | null;
    referenceId: string | null;
    gateway: string;
    pixKey: string | null;
};

export type AppControllerPingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/payment/ping';
};

export type AppControllerPingResponses = {
    default: string;
};

export type AppControllerPingResponse = AppControllerPingResponses[keyof AppControllerPingResponses];

export type TransactionsControllerCreateData = {
    body: CreateTransactionDto;
    path?: never;
    query?: never;
    url: '/payment/transactions';
};

export type TransactionsControllerCreateResponses = {
    default: GetTransactionDto;
};

export type TransactionsControllerCreateResponse = TransactionsControllerCreateResponses[keyof TransactionsControllerCreateResponses];

export type TransactionsControllerCreateFromDraftData = {
    body: CreateTransactionFromDraftDto;
    path?: never;
    query?: never;
    url: '/payment/transactions/from-draft';
};

export type TransactionsControllerCreateFromDraftResponses = {
    default: GetTransactionDto;
};

export type TransactionsControllerCreateFromDraftResponse = TransactionsControllerCreateFromDraftResponses[keyof TransactionsControllerCreateFromDraftResponses];

export type TransactionsControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/payment/transactions/{id}';
};

export type TransactionsControllerFindOneResponses = {
    default: GetTransactionDto;
};

export type TransactionsControllerFindOneResponse = TransactionsControllerFindOneResponses[keyof TransactionsControllerFindOneResponses];

export type TransactionsControllerFindByReferenceIdData = {
    body?: never;
    path: {
        referenceId: string;
    };
    query?: never;
    url: '/payment/transactions/reference/{referenceId}';
};

export type TransactionsControllerFindByReferenceIdResponses = {
    default: GetTransactionDto;
};

export type TransactionsControllerFindByReferenceIdResponse = TransactionsControllerFindByReferenceIdResponses[keyof TransactionsControllerFindByReferenceIdResponses];

export type TransactionsControllerRefundData = {
    body: RefundTransactionDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/payment/transactions/{id}/refund';
};

export type TransactionsControllerRefundResponses = {
    default: GetTransactionDto;
};

export type TransactionsControllerRefundResponse = TransactionsControllerRefundResponses[keyof TransactionsControllerRefundResponses];

export type EfiControllerHandleNotificationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/payment/webhook/efi/pix';
};

export type EfiControllerHandleNotificationResponses = {
    201: unknown;
};

export type EfiControllerBaseData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/payment/webhook/efi';
};

export type EfiControllerBaseResponses = {
    201: unknown;
};

export type DraftTransactionsControllerGetDraftTransactionData = {
    body?: never;
    path: {
        referenceId: string;
    };
    query?: never;
    url: '/payment/draft-transactions/{referenceId}';
};

export type DraftTransactionsControllerGetDraftTransactionResponses = {
    default: GetDraftTransactionDto;
};

export type DraftTransactionsControllerGetDraftTransactionResponse = DraftTransactionsControllerGetDraftTransactionResponses[keyof DraftTransactionsControllerGetDraftTransactionResponses];

export type DraftTransactionsControllerCreateDraftTransactionData = {
    body: CreateDraftTransactionDto;
    path?: never;
    query?: never;
    url: '/payment/draft-transactions';
};

export type DraftTransactionsControllerCreateDraftTransactionResponses = {
    default: GetDraftTransactionDto;
};

export type DraftTransactionsControllerCreateDraftTransactionResponse = DraftTransactionsControllerCreateDraftTransactionResponses[keyof DraftTransactionsControllerCreateDraftTransactionResponses];

export type TransfersControllerCreateData = {
    body: CreateTransferDto;
    path?: never;
    query?: never;
    url: '/payment/transfers';
};

export type TransfersControllerCreateResponses = {
    default: GetTransferDto;
};

export type TransfersControllerCreateResponse = TransfersControllerCreateResponses[keyof TransfersControllerCreateResponses];

export type TransfersControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/payment/transfers/{id}';
};

export type TransfersControllerFindOneResponses = {
    default: GetTransferDto;
};

export type TransfersControllerFindOneResponse = TransfersControllerFindOneResponses[keyof TransfersControllerFindOneResponses];
