// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type Object = {
    [key: string]: unknown;
};

export type GetAddressDto = {
    id: string;
    name: string;
    address: string;
    addressNum: string;
    addressAlt: string | null;
    neighborhood: string;
    city: string;
    state: string;
    country: string;
    zipcode: string;
};

export type GetEventDto = {
    id: string;
    name: string;
    tenantId: string;
    createdBy: string;
    startsAt: string;
    endsAt: string;
    isPrivate: boolean;
    isPublished: boolean;
    isCancelled: boolean;
    bannerImage: string;
    ticketImage: string | null;
    logoImage: string | null;
    sectionMapImage: string | null;
    qntMinPerCustomer: number;
    qntMaxPerCustomer: number;
    serviceFeeRate: number;
    isServiceFeeIncludedInTicketPrice: boolean;
    address: GetAddressDto;
};

export type GetPaginatedEventsDto = {
    data: Array<GetEventDto>;
    total: number;
    limit: number;
    offset: number;
};

export type GetBatchDto = {
    id: string;
    ticketsLimit: number;
    startTrigger: 'batch' | 'date' | 'manual';
    startsAt: string;
    endsAt: string;
    name: string;
    description: string | null;
    isPublished: boolean;
    isPublic: boolean;
    price: number;
    serviceFee: number | null;
    qntMinPerCustomer: number;
    qntMaxPerCustomer: number;
};

export type GetSectionWithBatchesDto = {
    id: string;
    name: string;
    description: string | null;
    capacity: number;
    isDisabled: boolean;
    isVisible: boolean;
    bannerImage: string | null;
    ticketImage: string | null;
    qntMinPerCustomer: number;
    qntMaxPerCustomer: number;
    batches: Array<GetBatchDto>;
};

export type GetEventWithSectionsAndBatchesDto = {
    id: string;
    name: string;
    tenantId: string;
    createdBy: string;
    startsAt: string;
    endsAt: string;
    isPrivate: boolean;
    isPublished: boolean;
    isCancelled: boolean;
    bannerImage: string;
    ticketImage: string | null;
    logoImage: string | null;
    sectionMapImage: string | null;
    qntMinPerCustomer: number;
    qntMaxPerCustomer: number;
    serviceFeeRate: number;
    isServiceFeeIncludedInTicketPrice: boolean;
    address: GetAddressDto;
    sections: Array<GetSectionWithBatchesDto>;
};

export type CreateEventDto = {
    name: string;
    startsAt: string;
    endsAt: string;
    isPrivate: boolean;
    isPublished: boolean;
    logoImage: string;
    bannerImage: string;
    ticketImage: string;
    sectionMapImage: string;
    qntMinPerCustomer: number;
    qntMaxPerCustomer: number;
    isServiceFeeIncludedInTicketPrice: boolean;
    address: string;
    pixKey: string;
};

export type GetSectionDto = {
    id: string;
    name: string;
    description: string | null;
    capacity: number;
    isDisabled: boolean;
    isVisible: boolean;
    bannerImage: string | null;
    ticketImage: string | null;
    qntMinPerCustomer: number;
    qntMaxPerCustomer: number;
};

export type GetEventWithSectionsDto = {
    id: string;
    name: string;
    tenantId: string;
    createdBy: string;
    startsAt: string;
    endsAt: string;
    isPrivate: boolean;
    isPublished: boolean;
    isCancelled: boolean;
    bannerImage: string;
    ticketImage: string | null;
    logoImage: string | null;
    sectionMapImage: string | null;
    qntMinPerCustomer: number;
    qntMaxPerCustomer: number;
    serviceFeeRate: number;
    isServiceFeeIncludedInTicketPrice: boolean;
    address: GetAddressDto;
    sections: Array<GetSectionDto>;
};

export type CreateAddressDto = {
    name: string;
    address: string;
    addressNum: string;
    addressAlt: string;
    neighborhood: string;
    city: string;
    state: string;
    country: string;
    zipcode: string;
};

export type EditAddressDto = {
    name: string;
    address: string;
    addressNum: string;
    addressAlt: string;
    neighborhood: string;
    city: string;
    state: string;
    country: string;
    zipcode: string;
};

export type GetTicketDto = {
    id: string;
    batch: GetBatchDto;
    ticketCode: string;
    firstName: string | null;
    lastName: string | null;
    email: string | null;
    status: 'open' | 'locked' | 'purchased' | 'used' | 'expired';
    adquireAt: string | null;
    adquireBy: string | null;
    usedAt: string | null;
    expiredAt: string | null;
    salePrice: number;
};

export type GetCustomFormFieldDto = {
    id: string;
    question: string;
    type: 'text' | 'textarea' | 'select' | 'radio' | 'date' | 'number' | 'email' | 'phone';
    options: Array<string> | null;
    required: boolean;
};

export type GetCustomFormDto = {
    id: string;
    name: string;
    description: string | null;
    fields: Array<GetCustomFormFieldDto>;
};

export type CreateCustomFormFieldDto = {
    question: string;
    type: 'text' | 'textarea' | 'select' | 'radio' | 'date' | 'number' | 'email' | 'phone';
    options: Array<string>;
    required: boolean;
};

export type CreateCustomFormDto = {
    name: string;
    description: string;
    fields: Array<CreateCustomFormFieldDto>;
};

export type GetBatchWithSectionDto = {
    id: string;
    ticketsLimit: number;
    startTrigger: 'batch' | 'date' | 'manual';
    startsAt: string;
    endsAt: string;
    name: string;
    description: string | null;
    isPublished: boolean;
    isPublic: boolean;
    price: number;
    serviceFee: number | null;
    qntMinPerCustomer: number;
    qntMaxPerCustomer: number;
    section: GetSectionDto;
};

export type CreateBatchDto = {
    section: string;
    ticketsLimit: number;
    startTrigger: 'batch' | 'date' | 'manual';
    startsAt: string;
    endsAt: string;
    name: string;
    description: string;
    isPublished: boolean;
    isPublic: boolean;
    price: number;
    qntMinPerCustomer: number;
    qntMaxPerCustomer: number;
    customForm?: string;
};

export type EditBatchDto = {
    startTrigger?: 'batch' | 'date' | 'manual';
    startsAt?: string;
    endsAt?: string;
    name?: string;
    description?: string;
    isPublished?: boolean;
    isPublic?: boolean;
    price?: number;
    qntMinPerCustomer?: number;
    qntMaxPerCustomer?: number;
    customForm?: string;
};

export type CreateSectionDto = {
    name: string;
    description: string;
    capacity: number;
    isDisabled: boolean;
    isVisible: boolean;
    bannerImage: string;
    ticketImage: string;
    qntMinPerCustomer: number;
    qntMaxPerCustomer: number;
    event: string;
};

export type CartTicketDto = {
    batchId: string;
    quantity: number;
};

export type CreateCartDto = {
    tickets: Array<CartTicketDto>;
};

export type GetCartDto = {
    id: string;
    userId: string;
    expiresAt: string | null;
    status: 'created' | 'expired' | 'cancelled' | 'checkout' | 'confirmed';
};

export type GetCartTicketDto = {
    id: string;
    salePrice: number;
    batchId: string;
    batchName: string;
    sectionName: string;
    customForm: GetCustomFormDto | null;
};

export type GetCartCouponDto = {
    couponCode: string;
    description: string | null;
    type: 'value' | 'percentage';
    value: number;
};

export type GetDetailedCartDto = {
    id: string;
    expiresAt: string;
    status: 'created' | 'expired' | 'cancelled' | 'checkout' | 'confirmed';
    orderId: string;
    originalTotal: number;
    totalServiceFee: number;
    finalTotal: number;
    discountAmount: number;
    tickets: Array<GetCartTicketDto>;
    coupon: GetCartCouponDto | null;
};

export type ApplyCouponDto = {
    couponCode: string | null;
};

export type TicketFormFiledResponseDto = {
    fieldId: string;
    value: string;
};

export type OrderTicket = {
    ticketId: string;
    firstName: string;
    lastName: string;
    email: string;
    responses: Array<TicketFormFiledResponseDto>;
};

export type CreateOrderDto = {
    cartId: string;
    firstName: string;
    lastName: string;
    email: string;
    tickets: Array<OrderTicket>;
};

export type GetOrderDto = {
    id: string;
    firstName: string;
    lastName: string;
    email: string;
    userId: string;
    paymentMethod: string;
    status: 'pending' | 'paid' | 'failed';
    cart: GetCartDto;
};

export type AllRequirementPropertiesDto = {
    batchId: string | null;
    eventId: string | null;
    sectionId: string | null;
    tenantId: string | null;
    userId: string | null;
    startsAt: string | null;
    expiresAt: string | null;
    value: number | null;
    quantities: number | null;
};

export type GetCouponRequirementsDto = {
    requirement: 'event-restriction' | 'section-restriction' | 'batch-restriction' | 'first-tenant-order' | 'first-event-order' | 'usage-limit' | 'minimum-price' | 'date-range';
    properties: AllRequirementPropertiesDto;
};

export type GetCouponDto = {
    id: string;
    couponCode: string;
    description: string | null;
    type: 'value' | 'percentage';
    value: number;
    requirements: Array<GetCouponRequirementsDto>;
    deleted: boolean;
    createdBy: string;
};

export type BaseRequirementProperties = {
    [key: string]: unknown;
};

export type CreateCouponRequirementsDto = {
    requirement: {
        [key: string]: unknown;
    };
    properties: BaseRequirementProperties;
};

export type CreateCouponDto = {
    couponCode: string;
    description: string;
    type: 'value' | 'percentage';
    value: number;
    requirements: Array<CreateCouponRequirementsDto>;
};

export type UpdateCouponDto = {
    description?: string;
    type?: 'value' | 'percentage';
    value?: number;
    requirements?: Array<CreateCouponRequirementsDto>;
};

export type AppControllerPingData = {
    body?: never;
    headers: {
        /**
         * The tenant id
         */
        'tenant-id': string;
    };
    path?: never;
    query?: never;
    url: '/tickets/ping';
};

export type AppControllerPingResponses = {
    default: string;
};

export type AppControllerPingResponse = AppControllerPingResponses[keyof AppControllerPingResponses];

export type EventControllerSearchAllPaginatedData = {
    body?: never;
    headers: {
        /**
         * The tenant id
         */
        'tenant-id': string;
    };
    path?: never;
    query?: {
        limit?: Object;
        offset?: Object;
        search?: string;
    };
    url: '/tickets/events/search';
};

export type EventControllerSearchAllPaginatedResponses = {
    default: GetPaginatedEventsDto;
};

export type EventControllerSearchAllPaginatedResponse = EventControllerSearchAllPaginatedResponses[keyof EventControllerSearchAllPaginatedResponses];

export type EventControllerFindAllData = {
    body?: never;
    headers: {
        /**
         * The tenant id
         */
        'tenant-id': string;
    };
    path?: never;
    query?: never;
    url: '/tickets/events';
};

export type EventControllerFindAllResponses = {
    default: Array<GetEventDto>;
};

export type EventControllerFindAllResponse = EventControllerFindAllResponses[keyof EventControllerFindAllResponses];

export type EventControllerCreateEventData = {
    body: CreateEventDto;
    headers: {
        /**
         * The tenant id
         */
        'tenant-id': string;
    };
    path?: never;
    query?: never;
    url: '/tickets/events';
};

export type EventControllerCreateEventResponses = {
    default: GetEventWithSectionsDto;
};

export type EventControllerCreateEventResponse = EventControllerCreateEventResponses[keyof EventControllerCreateEventResponses];

export type EventControllerFindOneData = {
    body?: never;
    headers: {
        /**
         * The tenant id
         */
        'tenant-id': string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/tickets/events/{id}';
};

export type EventControllerFindOneResponses = {
    default: GetEventWithSectionsAndBatchesDto;
};

export type EventControllerFindOneResponse = EventControllerFindOneResponses[keyof EventControllerFindOneResponses];

export type AddressControllerFindAllData = {
    body?: never;
    headers: {
        /**
         * The tenant id
         */
        'tenant-id': string;
    };
    path?: never;
    query?: never;
    url: '/tickets/address';
};

export type AddressControllerFindAllResponses = {
    default: Array<GetAddressDto>;
};

export type AddressControllerFindAllResponse = AddressControllerFindAllResponses[keyof AddressControllerFindAllResponses];

export type AddressControllerCreateAddressData = {
    body: CreateAddressDto;
    headers: {
        /**
         * The tenant id
         */
        'tenant-id': string;
    };
    path?: never;
    query?: never;
    url: '/tickets/address';
};

export type AddressControllerCreateAddressResponses = {
    default: GetAddressDto;
};

export type AddressControllerCreateAddressResponse = AddressControllerCreateAddressResponses[keyof AddressControllerCreateAddressResponses];

export type AddressControllerDeleteAddressData = {
    body?: never;
    headers: {
        /**
         * The tenant id
         */
        'tenant-id': string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/tickets/address/{id}';
};

export type AddressControllerDeleteAddressResponses = {
    200: unknown;
};

export type AddressControllerFindOneData = {
    body?: never;
    headers: {
        /**
         * The tenant id
         */
        'tenant-id': string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/tickets/address/{id}';
};

export type AddressControllerFindOneResponses = {
    default: GetAddressDto;
};

export type AddressControllerFindOneResponse = AddressControllerFindOneResponses[keyof AddressControllerFindOneResponses];

export type AddressControllerEditAddressData = {
    body: EditAddressDto;
    headers: {
        /**
         * The tenant id
         */
        'tenant-id': string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/tickets/address/{id}';
};

export type AddressControllerEditAddressResponses = {
    default: GetAddressDto;
};

export type AddressControllerEditAddressResponse = AddressControllerEditAddressResponses[keyof AddressControllerEditAddressResponses];

export type TicketControllerGetUserTicketsData = {
    body?: never;
    headers: {
        /**
         * The tenant id
         */
        'tenant-id': string;
    };
    path?: never;
    query?: never;
    url: '/tickets/tickets';
};

export type TicketControllerGetUserTicketsResponses = {
    default: GetTicketDto;
};

export type TicketControllerGetUserTicketsResponse = TicketControllerGetUserTicketsResponses[keyof TicketControllerGetUserTicketsResponses];

export type CustomFormControllerFindAllData = {
    body?: never;
    headers: {
        /**
         * The tenant id
         */
        'tenant-id': string;
    };
    path?: never;
    query?: never;
    url: '/tickets/custom-forms';
};

export type CustomFormControllerFindAllResponses = {
    default: Array<GetCustomFormDto>;
};

export type CustomFormControllerFindAllResponse = CustomFormControllerFindAllResponses[keyof CustomFormControllerFindAllResponses];

export type CustomFormControllerCreateCustomFormData = {
    body: CreateCustomFormDto;
    headers: {
        /**
         * The tenant id
         */
        'tenant-id': string;
    };
    path?: never;
    query?: never;
    url: '/tickets/custom-forms';
};

export type CustomFormControllerCreateCustomFormResponses = {
    default: GetCustomFormDto;
};

export type CustomFormControllerCreateCustomFormResponse = CustomFormControllerCreateCustomFormResponses[keyof CustomFormControllerCreateCustomFormResponses];

export type CustomFormControllerDeleteAddressData = {
    body?: never;
    headers: {
        /**
         * The tenant id
         */
        'tenant-id': string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/tickets/custom-forms/{id}';
};

export type CustomFormControllerDeleteAddressResponses = {
    200: unknown;
};

export type CustomFormControllerFindOneData = {
    body?: never;
    headers: {
        /**
         * The tenant id
         */
        'tenant-id': string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/tickets/custom-forms/{id}';
};

export type CustomFormControllerFindOneResponses = {
    default: GetCustomFormDto;
};

export type CustomFormControllerFindOneResponse = CustomFormControllerFindOneResponses[keyof CustomFormControllerFindOneResponses];

export type BatchControllerFindAllByEventData = {
    body?: never;
    headers: {
        /**
         * The tenant id
         */
        'tenant-id': string;
    };
    path: {
        eventId: string;
    };
    query?: never;
    url: '/tickets/batches/events/{eventId}';
};

export type BatchControllerFindAllByEventResponses = {
    default: Array<GetBatchWithSectionDto>;
};

export type BatchControllerFindAllByEventResponse = BatchControllerFindAllByEventResponses[keyof BatchControllerFindAllByEventResponses];

export type BatchControllerFindAllBySectionData = {
    body?: never;
    headers: {
        /**
         * The tenant id
         */
        'tenant-id': string;
    };
    path: {
        sectionId: string;
    };
    query?: never;
    url: '/tickets/batches/sections/{sectionId}';
};

export type BatchControllerFindAllBySectionResponses = {
    default: Array<GetBatchDto>;
};

export type BatchControllerFindAllBySectionResponse = BatchControllerFindAllBySectionResponses[keyof BatchControllerFindAllBySectionResponses];

export type BatchControllerDeleteBatchData = {
    body?: never;
    headers: {
        /**
         * The tenant id
         */
        'tenant-id': string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/tickets/batches/{id}';
};

export type BatchControllerDeleteBatchResponses = {
    200: unknown;
};

export type BatchControllerFindOneData = {
    body?: never;
    headers: {
        /**
         * The tenant id
         */
        'tenant-id': string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/tickets/batches/{id}';
};

export type BatchControllerFindOneResponses = {
    default: GetBatchDto;
};

export type BatchControllerFindOneResponse = BatchControllerFindOneResponses[keyof BatchControllerFindOneResponses];

export type BatchControllerEditBatchData = {
    body: EditBatchDto;
    headers: {
        /**
         * The tenant id
         */
        'tenant-id': string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/tickets/batches/{id}';
};

export type BatchControllerEditBatchResponses = {
    default: GetBatchWithSectionDto;
};

export type BatchControllerEditBatchResponse = BatchControllerEditBatchResponses[keyof BatchControllerEditBatchResponses];

export type BatchControllerCreateBatchData = {
    body: CreateBatchDto;
    headers: {
        /**
         * The tenant id
         */
        'tenant-id': string;
    };
    path?: never;
    query?: never;
    url: '/tickets/batches';
};

export type BatchControllerCreateBatchResponses = {
    default: GetBatchDto;
};

export type BatchControllerCreateBatchResponse = BatchControllerCreateBatchResponses[keyof BatchControllerCreateBatchResponses];

export type SectionControllerFindAllByEventData = {
    body?: never;
    headers: {
        /**
         * The tenant id
         */
        'tenant-id': string;
    };
    path: {
        eventId: string;
    };
    query?: never;
    url: '/tickets/sections/events/{eventId}';
};

export type SectionControllerFindAllByEventResponses = {
    default: Array<GetSectionWithBatchesDto>;
};

export type SectionControllerFindAllByEventResponse = SectionControllerFindAllByEventResponses[keyof SectionControllerFindAllByEventResponses];

export type SectionControllerDeleteAddressData = {
    body?: never;
    headers: {
        /**
         * The tenant id
         */
        'tenant-id': string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/tickets/sections/{id}';
};

export type SectionControllerDeleteAddressResponses = {
    200: unknown;
};

export type SectionControllerFindOneData = {
    body?: never;
    headers: {
        /**
         * The tenant id
         */
        'tenant-id': string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/tickets/sections/{id}';
};

export type SectionControllerFindOneResponses = {
    default: GetSectionDto;
};

export type SectionControllerFindOneResponse = SectionControllerFindOneResponses[keyof SectionControllerFindOneResponses];

export type SectionControllerCreateSectionData = {
    body: CreateSectionDto;
    headers: {
        /**
         * The tenant id
         */
        'tenant-id': string;
    };
    path?: never;
    query?: never;
    url: '/tickets/sections';
};

export type SectionControllerCreateSectionResponses = {
    default: GetSectionDto;
};

export type SectionControllerCreateSectionResponse = SectionControllerCreateSectionResponses[keyof SectionControllerCreateSectionResponses];

export type CartControllerCreateCartData = {
    body: CreateCartDto;
    headers: {
        /**
         * The tenant id
         */
        'tenant-id': string;
    };
    path?: never;
    query?: never;
    url: '/tickets/carts';
};

export type CartControllerCreateCartResponses = {
    default: GetCartDto;
};

export type CartControllerCreateCartResponse = CartControllerCreateCartResponses[keyof CartControllerCreateCartResponses];

export type CartControllerCancelCartData = {
    body?: never;
    headers: {
        /**
         * The tenant id
         */
        'tenant-id': string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/tickets/carts/{id}';
};

export type CartControllerCancelCartResponses = {
    200: unknown;
};

export type CartControllerGetCartData = {
    body?: never;
    headers: {
        /**
         * The tenant id
         */
        'tenant-id': string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/tickets/carts/{id}';
};

export type CartControllerGetCartResponses = {
    default: GetDetailedCartDto;
};

export type CartControllerGetCartResponse = CartControllerGetCartResponses[keyof CartControllerGetCartResponses];

export type CartControllerApplyCouponData = {
    body: ApplyCouponDto;
    headers: {
        /**
         * The tenant id
         */
        'tenant-id': string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/tickets/carts/{id}/apply-coupon';
};

export type CartControllerApplyCouponResponses = {
    default: GetDetailedCartDto;
};

export type CartControllerApplyCouponResponse = CartControllerApplyCouponResponses[keyof CartControllerApplyCouponResponses];

export type OrderControllerCreateOrderData = {
    body: CreateOrderDto;
    headers: {
        /**
         * The tenant id
         */
        'tenant-id': string;
    };
    path?: never;
    query?: never;
    url: '/tickets/orders';
};

export type OrderControllerCreateOrderResponses = {
    default: GetOrderDto;
};

export type OrderControllerCreateOrderResponse = OrderControllerCreateOrderResponses[keyof OrderControllerCreateOrderResponses];

export type OrderControllerCancelTicketData = {
    body?: never;
    headers: {
        /**
         * The tenant id
         */
        'tenant-id': string;
    };
    path: {
        orderId: string;
        ticketId: string;
    };
    query?: never;
    url: '/tickets/orders/{orderId}/tickets/{ticketId}/cancel';
};

export type OrderControllerCancelTicketResponses = {
    default: GetOrderDto;
};

export type OrderControllerCancelTicketResponse = OrderControllerCancelTicketResponses[keyof OrderControllerCancelTicketResponses];

export type CouponControllerFindAllData = {
    body?: never;
    headers: {
        /**
         * The tenant id
         */
        'tenant-id': string;
    };
    path?: never;
    query?: never;
    url: '/tickets/coupons';
};

export type CouponControllerFindAllResponses = {
    default: Array<GetCouponDto>;
};

export type CouponControllerFindAllResponse = CouponControllerFindAllResponses[keyof CouponControllerFindAllResponses];

export type CouponControllerCreateCouponData = {
    body: CreateCouponDto;
    headers: {
        /**
         * The tenant id
         */
        'tenant-id': string;
    };
    path?: never;
    query?: never;
    url: '/tickets/coupons';
};

export type CouponControllerCreateCouponResponses = {
    default: GetCouponDto;
};

export type CouponControllerCreateCouponResponse = CouponControllerCreateCouponResponses[keyof CouponControllerCreateCouponResponses];

export type CouponControllerDeleteCouponData = {
    body?: never;
    headers: {
        /**
         * The tenant id
         */
        'tenant-id': string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/tickets/coupons/{id}';
};

export type CouponControllerDeleteCouponResponses = {
    default: GetCouponDto;
};

export type CouponControllerDeleteCouponResponse = CouponControllerDeleteCouponResponses[keyof CouponControllerDeleteCouponResponses];

export type CouponControllerFindOneData = {
    body?: never;
    headers: {
        /**
         * The tenant id
         */
        'tenant-id': string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/tickets/coupons/{id}';
};

export type CouponControllerFindOneResponses = {
    default: GetCouponDto;
};

export type CouponControllerFindOneResponse = CouponControllerFindOneResponses[keyof CouponControllerFindOneResponses];

export type CouponControllerUpdateCouponData = {
    body: UpdateCouponDto;
    headers: {
        /**
         * The tenant id
         */
        'tenant-id': string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/tickets/coupons/{id}';
};

export type CouponControllerUpdateCouponResponses = {
    default: GetCouponDto;
};

export type CouponControllerUpdateCouponResponse = CouponControllerUpdateCouponResponses[keyof CouponControllerUpdateCouponResponses];
