// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AppControllerPingData, AppControllerPingResponses, LoginControllerGetLoggedUserData, LoginControllerGetLoggedUserResponses, LoginControllerLoginData, LoginControllerLoginResponses, LoginControllerRefreshTokenData, LoginControllerRefreshTokenResponses, TenantControllerCreateData, TenantControllerCreateResponses, TenantControllerFindAllData, TenantControllerFindAllResponses, TenantControllerFindOneData, TenantControllerFindOneResponses, TenantControllerUpdateData, TenantControllerUpdateResponses, UserControllerCreateData, UserControllerCreateResponses, UserControllerFindAllData, UserControllerFindAllResponses, UserControllerFindOneData, UserControllerFindOneResponses, UserControllerUpdateData, UserControllerUpdateResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const appControllerPing = <ThrowOnError extends boolean = false>(options: Options<AppControllerPingData, ThrowOnError>) => (options.client ?? client).get<AppControllerPingResponses, unknown, ThrowOnError>({ url: '/auth/ping', ...options });

export const loginControllerGetLoggedUser = <ThrowOnError extends boolean = false>(options: Options<LoginControllerGetLoggedUserData, ThrowOnError>) => (options.client ?? client).get<LoginControllerGetLoggedUserResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/login',
    ...options
});

export const loginControllerLogin = <ThrowOnError extends boolean = false>(options: Options<LoginControllerLoginData, ThrowOnError>) => (options.client ?? client).post<LoginControllerLoginResponses, unknown, ThrowOnError>({
    url: '/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const loginControllerRefreshToken = <ThrowOnError extends boolean = false>(options: Options<LoginControllerRefreshTokenData, ThrowOnError>) => (options.client ?? client).post<LoginControllerRefreshTokenResponses, unknown, ThrowOnError>({
    url: '/auth/login/refresh',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const tenantControllerFindAll = <ThrowOnError extends boolean = false>(options: Options<TenantControllerFindAllData, ThrowOnError>) => (options.client ?? client).get<TenantControllerFindAllResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/tenants',
    ...options
});

export const tenantControllerCreate = <ThrowOnError extends boolean = false>(options: Options<TenantControllerCreateData, ThrowOnError>) => (options.client ?? client).post<TenantControllerCreateResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/tenants',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const tenantControllerFindOne = <ThrowOnError extends boolean = false>(options: Options<TenantControllerFindOneData, ThrowOnError>) => (options.client ?? client).get<TenantControllerFindOneResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/tenants/{id}',
    ...options
});

export const tenantControllerUpdate = <ThrowOnError extends boolean = false>(options: Options<TenantControllerUpdateData, ThrowOnError>) => (options.client ?? client).patch<TenantControllerUpdateResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/tenants/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const userControllerFindAll = <ThrowOnError extends boolean = false>(options: Options<UserControllerFindAllData, ThrowOnError>) => (options.client ?? client).get<UserControllerFindAllResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/users',
    ...options
});

export const userControllerCreate = <ThrowOnError extends boolean = false>(options: Options<UserControllerCreateData, ThrowOnError>) => (options.client ?? client).post<UserControllerCreateResponses, unknown, ThrowOnError>({
    url: '/auth/users',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const userControllerFindOne = <ThrowOnError extends boolean = false>(options: Options<UserControllerFindOneData, ThrowOnError>) => (options.client ?? client).get<UserControllerFindOneResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/users/{id}',
    ...options
});

export const userControllerUpdate = <ThrowOnError extends boolean = false>(options: Options<UserControllerUpdateData, ThrowOnError>) => (options.client ?? client).patch<UserControllerUpdateResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/users/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
