// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type LoginRequestBody = {
    email: string;
    password: string;
};

export type UserTokenResponseDto = {
    access_token: string;
    expires_in: number;
    refresh_expires_in: number;
    refresh_token: string;
    token_type: string;
    'not-before-policy': number;
    session_state: string;
    scope: string;
};

export type RefreshTokenRequestBody = {
    /**
     * The refresh jwt token
     */
    refresh_token: string;
};

export type UserDataResponseDto = {
    id: string;
    email: string;
    name: string;
    roles: Array<'customer' | 'admin' | 'account-manager' | 'commercial' | 'ticket-reader'>;
};

export type CreateTenantDto = {
    name: string;
    displayName: string;
    pixKey: string;
};

export type GetTenantDto = {
    id: string;
    name: string;
};

export type UpdateTenantDto = {
    name: string;
    displayName: string;
    pixKey: string;
};

export type ResponseOfUpdateTenantDto = {
    name: string;
};

export type CreateUserDto = {
    email: string;
    firstName: string;
    lastName: string;
    password: string;
    phone: string;
};

export type GetUserDto = {
    id: string;
    username: string;
    email: string;
    firstName: string;
    lastName: string;
};

export type UpdateUserDto = {
    email: string;
    firstName: string;
    lastName: string;
};

export type AppControllerPingData = {
    body?: never;
    headers: {
        /**
         * The tenant id
         */
        'tenant-id': string;
    };
    path?: never;
    query?: never;
    url: '/auth/ping';
};

export type AppControllerPingResponses = {
    default: string;
};

export type AppControllerPingResponse = AppControllerPingResponses[keyof AppControllerPingResponses];

export type LoginControllerGetLoggedUserData = {
    body?: never;
    headers: {
        /**
         * The tenant id
         */
        'tenant-id': string;
    };
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginControllerGetLoggedUserResponses = {
    default: UserDataResponseDto;
};

export type LoginControllerGetLoggedUserResponse = LoginControllerGetLoggedUserResponses[keyof LoginControllerGetLoggedUserResponses];

export type LoginControllerLoginData = {
    body: LoginRequestBody;
    headers: {
        /**
         * The tenant id
         */
        'tenant-id': string;
    };
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginControllerLoginResponses = {
    default: UserTokenResponseDto;
};

export type LoginControllerLoginResponse = LoginControllerLoginResponses[keyof LoginControllerLoginResponses];

export type LoginControllerRefreshTokenData = {
    body: RefreshTokenRequestBody;
    headers: {
        /**
         * The tenant id
         */
        'tenant-id': string;
    };
    path?: never;
    query?: never;
    url: '/auth/login/refresh';
};

export type LoginControllerRefreshTokenResponses = {
    default: UserTokenResponseDto;
};

export type LoginControllerRefreshTokenResponse = LoginControllerRefreshTokenResponses[keyof LoginControllerRefreshTokenResponses];

export type TenantControllerFindAllData = {
    body?: never;
    headers: {
        /**
         * The tenant id
         */
        'tenant-id': string;
    };
    path?: never;
    query?: never;
    url: '/auth/tenants';
};

export type TenantControllerFindAllResponses = {
    default: Array<GetTenantDto>;
};

export type TenantControllerFindAllResponse = TenantControllerFindAllResponses[keyof TenantControllerFindAllResponses];

export type TenantControllerCreateData = {
    body: CreateTenantDto;
    headers: {
        /**
         * The tenant id
         */
        'tenant-id': string;
    };
    path?: never;
    query?: never;
    url: '/auth/tenants';
};

export type TenantControllerCreateResponses = {
    201: unknown;
};

export type TenantControllerFindOneData = {
    body?: never;
    headers: {
        /**
         * The tenant id
         */
        'tenant-id': string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/auth/tenants/{id}';
};

export type TenantControllerFindOneResponses = {
    default: GetTenantDto;
};

export type TenantControllerFindOneResponse = TenantControllerFindOneResponses[keyof TenantControllerFindOneResponses];

export type TenantControllerUpdateData = {
    body: UpdateTenantDto;
    headers: {
        /**
         * The tenant id
         */
        'tenant-id': string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/auth/tenants/{id}';
};

export type TenantControllerUpdateResponses = {
    default: ResponseOfUpdateTenantDto;
};

export type TenantControllerUpdateResponse = TenantControllerUpdateResponses[keyof TenantControllerUpdateResponses];

export type UserControllerFindAllData = {
    body?: never;
    headers: {
        /**
         * The tenant id
         */
        'tenant-id': string;
    };
    path?: never;
    query?: never;
    url: '/auth/users';
};

export type UserControllerFindAllResponses = {
    default: Array<GetUserDto>;
};

export type UserControllerFindAllResponse = UserControllerFindAllResponses[keyof UserControllerFindAllResponses];

export type UserControllerCreateData = {
    body: CreateUserDto;
    headers: {
        /**
         * The tenant id
         */
        'tenant-id': string;
    };
    path?: never;
    query?: never;
    url: '/auth/users';
};

export type UserControllerCreateResponses = {
    default: GetUserDto;
};

export type UserControllerCreateResponse = UserControllerCreateResponses[keyof UserControllerCreateResponses];

export type UserControllerFindOneData = {
    body?: never;
    headers: {
        /**
         * The tenant id
         */
        'tenant-id': string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/auth/users/{id}';
};

export type UserControllerFindOneResponses = {
    default: GetUserDto;
};

export type UserControllerFindOneResponse = UserControllerFindOneResponses[keyof UserControllerFindOneResponses];

export type UserControllerUpdateData = {
    body: UpdateUserDto;
    headers: {
        /**
         * The tenant id
         */
        'tenant-id': string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/auth/users/{id}';
};

export type UserControllerUpdateResponses = {
    default: GetUserDto;
};

export type UserControllerUpdateResponse = UserControllerUpdateResponses[keyof UserControllerUpdateResponses];
